"""empty message

Revision ID: 576fd6c538af
Revises: 
Create Date: 2020-09-26 23:31:12.696495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576fd6c538af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    # ### end Alembic commands ###
